export const createDefaultSettingsForm = () => ({
  hotelName: 'LuxuryStay Downtown',
  brandName: 'LuxuryStay Hospitality',
  contactEmail: 'hello@luxurystay.com',
  contactPhone: '+92-300-0000000',
  address: 'Luxury Avenue, Clifton, Karachi',
  contactChannels: {
    supportEmail: 'support@luxurystay.com',
    reservationsEmail: 'reservations@luxurystay.com',
    reservationsPhone: '+92-300-1111111',
    whatsappPhone: '+92-300-2222222',
  },
  currency: 'PKR',
  timezone: 'Asia/Karachi',
  taxRules: [{ name: 'Hotel Tax', percentage: 13, appliesTo: 'room_nights' }],
  checkInTime: '14:00',
  checkOutTime: '12:00',
  nightAuditTime: '02:00',
  cancellationPolicy: 'Free cancellation up to 24 hours before arrival.',
  invoiceTerms: 'Payments are due upon checkout unless corporate billing is approved.',
  logoUrl: null,
  faviconUrl: null,
  scrollToTopUrl: null,
  websiteSettings: {
    heroTitle: 'A warmer kind of five-star city stay.',
    heroSubtitle: 'Discover suites, dining, wellness, and a reservation journey shaped to feel calm, refined, and beautifully paced from the very first click.',
    footerDescription: 'LuxuryStay Hospitality blends boutique warmth, five-star ease, and polished guest care across every arrival, suite, and signature stay.',
    mapEmbedUrl: '',
    heroGalleryUrls: [],
    aboutHeroImageUrl: '',
    storyImageUrl: '',
    diningImageUrl: '',
    wellnessImageUrl: '',
    eventsImageUrl: '',
    destinationImageUrl: '',
    contactImageUrl: '',
    galleryHighlightUrl: '',
    faqHeroImageUrl: '',
    loginHeroImageUrl: '',
    registerHeroImageUrl: '',
  },
  seoSettings: {
    metaTitle: 'LuxuryStay Hospitality | Luxury Hotel, Suites, Dining, and Reservations',
    metaDescription: 'Discover a premium hotel website experience with refined suites, signature dining, seamless reservations, and five-star hospitality.',
    metaKeywords: 'luxury hotel, hotel suites, five star hotel, hotel booking, premium hospitality, boutique hotel',
  },
  aboutPageSettings: {
    diningExperience: { title: 'Late-evening dining with a city-facing table', description: 'Seasonal menus, private dining corners, and service paced for long conversations rather than rushed tables.', imageUrl: '' },
    wellnessExperience: { title: 'A slower rhythm for mornings, recovery, and reset', description: 'Wellness rituals, in-room comfort, and restorative amenities that make every stay feel intentionally paced.', imageUrl: '' },
    eventsExperience: { title: 'Gatherings that feel polished before the first guest arrives', description: 'Boardroom precision, celebration-ready styling, and hosting support carried with calm confidence.', imageUrl: '' },
  },
  homePageSettings: {
    aboutPrimaryImageUrl: '',
    aboutSecondaryImageUrl: '',
  },
  amenitiesPageSettings: {
    primaryImageUrl: '',
    secondaryImageUrl: '',
    highlight1: { title: 'Quiet foundation', description: 'Every detail in our suites serves a purpose, creating an effortless surrounding without visual noise.' },
    highlight2: { title: 'Considered arrival', description: 'Check-in is handled personally, designed to lower heart rates and set a composed tone from the first minute.' },
    highlight3: { title: 'Unseen care', description: 'Housekeeping and service touchpoints are almost invisible, leaving room for absolute calm during your stay.' },
  },
  socialLinks: {
    facebook: '',
    instagram: '',
    linkedin: '',
    x: '',
    youtube: '',
  },
  bookingSettings: {
    onlineBookingEnabled: true,
    allowGuestRegistration: true,
    showPublicPricing: true,
    requireApprovalForOnlineBookings: false,
  },
  notificationSettings: {
    guestBookingAlertsEnabled: true,
    adminBroadcastsEnabled: true,
    housekeepingCheckoutAlertsEnabled: true,
    maintenanceEscalationAlertsEnabled: true,
  },
  themeSettings: {
    primaryColor: '#10243f',
    accentColor: '#b88c4a',
    darkModeEnabled: true,
  },
});

export const mergeSettingsForm = (data) => ({
  ...createDefaultSettingsForm(),
  ...(data ?? {}),
  taxRules: data?.taxRules?.length ? data.taxRules : createDefaultSettingsForm().taxRules,
  contactChannels: {
    ...createDefaultSettingsForm().contactChannels,
    ...(data?.contactChannels ?? {}),
  },
  websiteSettings: {
    ...createDefaultSettingsForm().websiteSettings,
    ...(data?.websiteSettings ?? {}),
  },
  seoSettings: {
    ...createDefaultSettingsForm().seoSettings,
    ...(data?.seoSettings ?? {}),
  },
  aboutPageSettings: {
    diningExperience: {
        ...createDefaultSettingsForm().aboutPageSettings.diningExperience,
        ...(data?.aboutPageSettings?.diningExperience ?? {}),
        imageUrl: data?.aboutPageSettings?.diningExperience?.imageUrl || data?.websiteSettings?.diningImageUrl || '',
    },
    wellnessExperience: {
        ...createDefaultSettingsForm().aboutPageSettings.wellnessExperience,
        ...(data?.aboutPageSettings?.wellnessExperience ?? {}),
        imageUrl: data?.aboutPageSettings?.wellnessExperience?.imageUrl || data?.websiteSettings?.wellnessImageUrl || '',
    },
    eventsExperience: {
        ...createDefaultSettingsForm().aboutPageSettings.eventsExperience,
        ...(data?.aboutPageSettings?.eventsExperience ?? {}),
        imageUrl: data?.aboutPageSettings?.eventsExperience?.imageUrl || data?.websiteSettings?.eventsImageUrl || '',
    },
  },
  homePageSettings: {
    ...createDefaultSettingsForm().homePageSettings,
    ...(data?.homePageSettings ?? {}),
  },
  amenitiesPageSettings: {
    ...createDefaultSettingsForm().amenitiesPageSettings,
    ...(data?.amenitiesPageSettings ?? {}),
    highlight1: { ...createDefaultSettingsForm().amenitiesPageSettings.highlight1, ...(data?.amenitiesPageSettings?.highlight1 ?? {}) },
    highlight2: { ...createDefaultSettingsForm().amenitiesPageSettings.highlight2, ...(data?.amenitiesPageSettings?.highlight2 ?? {}) },
    highlight3: { ...createDefaultSettingsForm().amenitiesPageSettings.highlight3, ...(data?.amenitiesPageSettings?.highlight3 ?? {}) },
  },
  socialLinks: {
    ...createDefaultSettingsForm().socialLinks,
    ...(data?.socialLinks ?? {}),
  },
  bookingSettings: {
    ...createDefaultSettingsForm().bookingSettings,
    ...(data?.bookingSettings ?? {}),
  },
  notificationSettings: {
    ...createDefaultSettingsForm().notificationSettings,
    ...(data?.notificationSettings ?? {}),
  },
  themeSettings: {
    ...createDefaultSettingsForm().themeSettings,
    ...(data?.themeSettings ?? {}),
  },
});

export const buildSettingsPayload = (form) => ({
  hotelName: form.hotelName,
  brandName: form.brandName,
  contactEmail: form.contactEmail,
  contactPhone: form.contactPhone,
  address: form.address,
  contactChannels: {
    supportEmail: form.contactChannels?.supportEmail?.trim() || '',
    reservationsEmail: form.contactChannels?.reservationsEmail?.trim() || '',
    reservationsPhone: form.contactChannels?.reservationsPhone?.trim() || '',
    whatsappPhone: form.contactChannels?.whatsappPhone?.trim() || '',
  },
  currency: form.currency,
  timezone: form.timezone,
  checkInTime: form.checkInTime,
  checkOutTime: form.checkOutTime,
  nightAuditTime: form.nightAuditTime,
  cancellationPolicy: form.cancellationPolicy,
  invoiceTerms: form.invoiceTerms,
  logoUrl: form.logoUrl || null,
  faviconUrl: form.faviconUrl || null,
  scrollToTopUrl: form.scrollToTopUrl || null,
  websiteSettings: {
    heroTitle: form.websiteSettings?.heroTitle?.trim() || '',
    heroSubtitle: form.websiteSettings?.heroSubtitle?.trim() || '',
    footerDescription: form.websiteSettings?.footerDescription?.trim() || '',
    mapEmbedUrl: form.websiteSettings?.mapEmbedUrl?.trim() || '',
    heroGalleryUrls: (form.websiteSettings?.heroGalleryUrls ?? []).filter(Boolean),
    aboutHeroImageUrl: form.websiteSettings?.aboutHeroImageUrl?.trim() || '',
    storyImageUrl: form.websiteSettings?.storyImageUrl?.trim() || '',
    diningImageUrl: form.websiteSettings?.diningImageUrl?.trim() || '',
    wellnessImageUrl: form.websiteSettings?.wellnessImageUrl?.trim() || '',
    eventsImageUrl: form.websiteSettings?.eventsImageUrl?.trim() || '',
    destinationImageUrl: form.websiteSettings?.destinationImageUrl?.trim() || '',
    contactImageUrl: form.websiteSettings?.contactImageUrl?.trim() || '',
    galleryHighlightUrl: form.websiteSettings?.galleryHighlightUrl?.trim() || '',
    faqHeroImageUrl: form.websiteSettings?.faqHeroImageUrl?.trim() || '',
    loginHeroImageUrl: form.websiteSettings?.loginHeroImageUrl?.trim() || '',
    registerHeroImageUrl: form.websiteSettings?.registerHeroImageUrl?.trim() || '',
  },
  seoSettings: {
    metaTitle: form.seoSettings?.metaTitle?.trim() || '',
    metaDescription: form.seoSettings?.metaDescription?.trim() || '',
    metaKeywords: form.seoSettings?.metaKeywords?.trim() || '',
  },
  aboutPageSettings: {
    diningExperience: {
        title: form.aboutPageSettings?.diningExperience?.title?.trim() || '',
        description: form.aboutPageSettings?.diningExperience?.description?.trim() || '',
        imageUrl: form.aboutPageSettings?.diningExperience?.imageUrl?.trim() || '',
    },
    wellnessExperience: {
        title: form.aboutPageSettings?.wellnessExperience?.title?.trim() || '',
        description: form.aboutPageSettings?.wellnessExperience?.description?.trim() || '',
        imageUrl: form.aboutPageSettings?.wellnessExperience?.imageUrl?.trim() || '',
    },
    eventsExperience: {
        title: form.aboutPageSettings?.eventsExperience?.title?.trim() || '',
        description: form.aboutPageSettings?.eventsExperience?.description?.trim() || '',
        imageUrl: form.aboutPageSettings?.eventsExperience?.imageUrl?.trim() || '',
    },
  },
  homePageSettings: {
    aboutPrimaryImageUrl: form.homePageSettings?.aboutPrimaryImageUrl?.trim() || '',
    aboutSecondaryImageUrl: form.homePageSettings?.aboutSecondaryImageUrl?.trim() || '',
  },
  amenitiesPageSettings: {
    primaryImageUrl: form.amenitiesPageSettings?.primaryImageUrl?.trim() || '',
    secondaryImageUrl: form.amenitiesPageSettings?.secondaryImageUrl?.trim() || '',
    highlight1: {
        title: form.amenitiesPageSettings?.highlight1?.title?.trim() || '',
        description: form.amenitiesPageSettings?.highlight1?.description?.trim() || '',
    },
    highlight2: {
        title: form.amenitiesPageSettings?.highlight2?.title?.trim() || '',
        description: form.amenitiesPageSettings?.highlight2?.description?.trim() || '',
    },
    highlight3: {
        title: form.amenitiesPageSettings?.highlight3?.title?.trim() || '',
        description: form.amenitiesPageSettings?.highlight3?.description?.trim() || '',
    },
  },
  socialLinks: {
    facebook: form.socialLinks?.facebook?.trim() || '',
    instagram: form.socialLinks?.instagram?.trim() || '',
    linkedin: form.socialLinks?.linkedin?.trim() || '',
    x: form.socialLinks?.x?.trim() || '',
    youtube: form.socialLinks?.youtube?.trim() || '',
  },
  bookingSettings: {
    onlineBookingEnabled: Boolean(form.bookingSettings?.onlineBookingEnabled),
    allowGuestRegistration: Boolean(form.bookingSettings?.allowGuestRegistration),
    showPublicPricing: Boolean(form.bookingSettings?.showPublicPricing),
    requireApprovalForOnlineBookings: Boolean(form.bookingSettings?.requireApprovalForOnlineBookings),
  },
  notificationSettings: {
    guestBookingAlertsEnabled: Boolean(form.notificationSettings?.guestBookingAlertsEnabled),
    adminBroadcastsEnabled: Boolean(form.notificationSettings?.adminBroadcastsEnabled),
    housekeepingCheckoutAlertsEnabled: Boolean(form.notificationSettings?.housekeepingCheckoutAlertsEnabled),
    maintenanceEscalationAlertsEnabled: Boolean(form.notificationSettings?.maintenanceEscalationAlertsEnabled),
  },
  taxRules: form.taxRules,
  themeSettings: form.themeSettings,
});
