import { Router } from 'express';
import { authenticate } from '../../shared/middleware/authenticate.js';
import { requirePermissions } from '../../shared/middleware/authorize.js';
import { validate } from '../../shared/middleware/validate.js';
import { asyncHandler } from '../../shared/utils/async-handler.js';
import { folioChargeController, invoiceController, paymentController } from './billing.controller.js';
import { createFolioChargeSchema, createPaymentSchema, finalizeInvoiceSchema, folioChargeIdParamsSchema, invoiceIdParamsSchema, listFolioChargesSchema, listInvoicesSchema, listPaymentsSchema, paymentIdParamsSchema, reservationIdParamsSchema, updateFolioChargeSchema, } from './billing.validation.js';
export const folioChargesRouter = Router();
export const invoicesRouter = Router();
export const paymentsRouter = Router();
folioChargesRouter.use(authenticate);
folioChargesRouter.get('/', requirePermissions('folioCharges.read'), validate(listFolioChargesSchema), asyncHandler(folioChargeController.list));
folioChargesRouter.post('/', requirePermissions('folioCharges.create'), validate(createFolioChargeSchema), asyncHandler(folioChargeController.create));
folioChargesRouter.patch('/:chargeId', requirePermissions('folioCharges.update'), validate(folioChargeIdParamsSchema), validate(updateFolioChargeSchema), asyncHandler(folioChargeController.update));
folioChargesRouter.delete('/:chargeId', requirePermissions('folioCharges.delete'), validate(folioChargeIdParamsSchema), asyncHandler(folioChargeController.remove));
invoicesRouter.use(authenticate);
invoicesRouter.get('/', requirePermissions('invoices.read'), validate(listInvoicesSchema), asyncHandler(invoiceController.list));
invoicesRouter.get('/:invoiceId', requirePermissions('invoices.read'), validate(invoiceIdParamsSchema), asyncHandler(invoiceController.getById));
invoicesRouter.post('/generate/:reservationId', requirePermissions('invoices.create'), validate(reservationIdParamsSchema), asyncHandler(invoiceController.generate));
invoicesRouter.post('/:invoiceId/finalize', requirePermissions('invoices.finalize'), validate(invoiceIdParamsSchema), validate(finalizeInvoiceSchema), asyncHandler(invoiceController.finalize));
paymentsRouter.use(authenticate);
paymentsRouter.get('/', requirePermissions('payments.read'), validate(listPaymentsSchema), asyncHandler(paymentController.list));
paymentsRouter.get('/:paymentId', requirePermissions('payments.read'), validate(paymentIdParamsSchema), asyncHandler(paymentController.getById));
paymentsRouter.post('/', requirePermissions('payments.create'), validate(createPaymentSchema), asyncHandler(paymentController.create));
