import { Router } from 'express';
import { authenticate } from '../../shared/middleware/authenticate.js';
import { requirePermissions } from '../../shared/middleware/authorize.js';
import { validate } from '../../shared/middleware/validate.js';
import { asyncHandler } from '../../shared/utils/async-handler.js';
import { reservationController } from './reservation.controller.js';
import { amendStaySchema, assignRoomSchema, cancelReservationSchema, checkInReservationSchema, checkOutReservationSchema, createReservationSchema, listReservationsSchema, reservationIdParamsSchema, updateReservationSchema, } from './reservation.validation.js';
export const reservationsRouter = Router();
reservationsRouter.use(authenticate);
reservationsRouter.get('/', requirePermissions('reservations.read'), validate(listReservationsSchema), asyncHandler(reservationController.list));
reservationsRouter.get('/:reservationId', requirePermissions('reservations.read'), validate(reservationIdParamsSchema), asyncHandler(reservationController.getById));
reservationsRouter.post('/', requirePermissions('reservations.create'), validate(createReservationSchema), asyncHandler(reservationController.create));
reservationsRouter.patch('/:reservationId', requirePermissions('reservations.update'), validate(reservationIdParamsSchema), validate(updateReservationSchema), asyncHandler(reservationController.update));
reservationsRouter.patch('/:reservationId/amend-stay', requirePermissions('reservations.update'), validate(reservationIdParamsSchema), validate(amendStaySchema), asyncHandler(reservationController.amendStay));
reservationsRouter.post('/:reservationId/confirm', requirePermissions('reservations.confirm'), validate(reservationIdParamsSchema), asyncHandler(reservationController.confirm));
reservationsRouter.post('/:reservationId/assign-room', requirePermissions('reservations.assignRoom'), validate(reservationIdParamsSchema), validate(assignRoomSchema), asyncHandler(reservationController.assignRoom));
reservationsRouter.post('/:reservationId/cancel', requirePermissions('reservations.cancel'), validate(reservationIdParamsSchema), validate(cancelReservationSchema), asyncHandler(reservationController.cancel));
reservationsRouter.post('/:reservationId/missed-arrival', requirePermissions('reservations.update'), validate(reservationIdParamsSchema), asyncHandler(reservationController.markAsMissedArrival));
reservationsRouter.post('/:reservationId/check-in', requirePermissions('checkIn.update'), validate(reservationIdParamsSchema), validate(checkInReservationSchema), asyncHandler(reservationController.checkIn));
reservationsRouter.post('/:reservationId/check-out', requirePermissions('checkOut.update'), validate(reservationIdParamsSchema), validate(checkOutReservationSchema), asyncHandler(reservationController.checkOut));
