import { Schema, model } from 'mongoose';
const settingSchema = new Schema({
    hotelName: { type: String, required: true },
    brandName: { type: String, required: true },
    contactEmail: { type: String, required: true },
    contactPhone: { type: String, required: true },
    address: { type: String, required: true },
    contactChannels: {
        supportEmail: { type: String, default: '' },
        reservationsEmail: { type: String, default: '' },
        reservationsPhone: { type: String, default: '' },
        whatsappPhone: { type: String, default: '' },
    },
    currency: { type: String, required: true, default: 'PKR' },
    timezone: { type: String, required: true, default: 'Asia/Karachi' },
    taxRules: {
        type: [
            {
                name: { type: String, required: true },
                percentage: { type: Number, required: true, min: 0 },
                appliesTo: { type: String, required: true },
            },
        ],
        default: [],
    },
    checkInTime: { type: String, required: true, default: '14:00' },
    checkOutTime: { type: String, required: true, default: '12:00' },
    cancellationPolicy: { type: String, required: true },
    invoiceTerms: { type: String, required: true },
    logoUrl: { type: String, default: null },
    faviconUrl: { type: String, default: null },
    scrollToTopUrl: { type: String, default: null },
    websiteSettings: {
        heroTitle: { type: String, default: '' },
        heroSubtitle: { type: String, default: '' },
        footerDescription: { type: String, default: '' },
        mapEmbedUrl: { type: String, default: '' },
        heroGalleryUrls: { type: [String], default: [] },
        aboutHeroImageUrl: { type: String, default: '' },
        storyImageUrl: { type: String, default: '' },
        diningImageUrl: { type: String, default: '' },
        wellnessImageUrl: { type: String, default: '' },
        eventsImageUrl: { type: String, default: '' },
        destinationImageUrl: { type: String, default: '' },
        contactImageUrl: { type: String, default: '' },
        galleryHighlightUrl: { type: String, default: '' },
        faqHeroImageUrl: { type: String, default: '' },
        loginHeroImageUrl: { type: String, default: '' },
        registerHeroImageUrl: { type: String, default: '' },
    },
    seoSettings: {
        metaTitle: { type: String, default: '' },
        metaDescription: { type: String, default: '' },
        metaKeywords: { type: String, default: '' },
    },
    socialLinks: {
        facebook: { type: String, default: '' },
        instagram: { type: String, default: '' },
        linkedin: { type: String, default: '' },
        x: { type: String, default: '' },
        youtube: { type: String, default: '' },
    },
    bookingSettings: {
        onlineBookingEnabled: { type: Boolean, default: true },
        allowGuestRegistration: { type: Boolean, default: true },
        showPublicPricing: { type: Boolean, default: true },
        requireApprovalForOnlineBookings: { type: Boolean, default: false },
    },
    notificationSettings: {
        guestBookingAlertsEnabled: { type: Boolean, default: true },
        adminBroadcastsEnabled: { type: Boolean, default: true },
        housekeepingCheckoutAlertsEnabled: { type: Boolean, default: true },
        maintenanceEscalationAlertsEnabled: { type: Boolean, default: true },
    },
    themeSettings: {
        primaryColor: { type: String, default: '#10243f' },
        accentColor: { type: String, default: '#b88c4a' },
        darkModeEnabled: { type: Boolean, default: false },
    },
    updatedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
}, { timestamps: true });
export const SettingModel = model('Setting', settingSchema);
